export const REQUEST_API_ALL_POKEMON = 'REQUEST_API_ALL_POKEMON'
export const RECEIVE_API_ALL_POKEMON = 'RECEIVE_API_ALL_POKEMON'
export const REQUEST_API_POKEMON = 'REQUEST_API_POKEMON'
export const RECEIVE_API_POKEMON = 'RECEIVE_API_POKEMON'

export const REQUEST_API_QUERY_EDAMAM = 'REQUEST_API_QUERY_EDAMAM'
export const RECEIVE_API_QUERT_EDAMAM = 'RECEIVE_API_QUERT_EDAMAM'

export const REQUEST_API_QUERY_SPOONACULAR = 'REQUEST_API_QUERY_SPOONACULAR'
export const RECEIVE_API_QUERY_SPOONACULAR = 'RECEIVE_API_QUERY_SPOONACULAR'
export const REQUEST_API_RECIPE_INFO = 'REQUEST_API_RECIPE_INFO'
export const RECEIVE_API_RECIPE_INFO = 'RECEIVE_API_RECIPE_INFO'

export const SET_ERROR = 'SET_ERROR'
