export const REQUEST_API_ALL_POKEMON = 'REQUEST_API_ALL_POKEMON'
export const RECEIVE_API_ALL_POKEMON = 'RECEIVE_API_ALL_POKEMON'
export const REQUEST_API_POKEMON = 'REQUEST_API_POKEMON'
export const RECEIVE_API_POKEMON = 'RECEIVE_API_POKEMON'
